### ISSUE TITLE
Exception trying to run from battle

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#44]
It was from a battle with daemon lord.
Traceback (most recent call last):??????? ^* *** encounter ***               ^
  File "/home/achiwa/py/dl/dl.py", line 5098, in <module>
    main()
  File "/home/achiwa/py/dl/dl.py", line 5094, in main
    dispatch(game)
  File "/home/achiwa/py/dl/dl.py", line 5068, in dispatch
    maze(game)
  File "/home/achiwa/py/dl/dl.py", line 4942, in maze
    game.battle.battle()
  File "/home/achiwa/py/dl/dl.py", line 3490, in battle
    self.game.spell.cast_spell_dispatch(
  File "/home/achiwa/py/dl/dl.py", line 1634, in cast_spell_dispatch
    self.etc(invoker, spell, target)
  File "/home/achiwa/py/dl/dl.py", line 1725, in etc
    damage = max(target.hp - random.randint(7) - 1, 0)
TypeError: randint() missing 1 required positional argument: 'b'

**Comment by achiwa912** [comment]
Looks like, party members never got 'hinshi' spell from monsters.  Fixed.  Need to verify.

**Comment by achiwa912** [comment]
Verified the fix.
