### ISSUE TITLE
'shisubeshi' doesn't work

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#45]

**Comment by achiwa912** [comment]
Fixed spell definition in spells.csv

**Comment by achiwa912** [comment]
Reopening.  Saw an exception.
Traceback (most recent call last):        ^                                  ^
  File "/home/achiwa/py/dl/dl.py", line 5101, in <module>
    main()
  File "/home/achiwa/py/dl/dl.py", line 5097, in main
    dispatch(game)
  File "/home/achiwa/py/dl/dl.py", line 5071, in dispatch
    maze(game)
  File "/home/achiwa/py/dl/dl.py", line 4945, in maze
    game.battle.battle()
  File "/home/achiwa/py/dl/dl.py", line 3493, in battle
    self.game.spell.cast_spell_dispatch(
  File "/home/achiwa/py/dl/dl.py", line 1626, in cast_spell_dispatch
    self.attack(invoker, spell, target)
  File "/home/achiwa/py/dl/dl.py", line 1937, in attack
    self.death_single(target, disptarget)
  File "/home/achiwa/py/dl/dl.py", line 1858, in death_single
    regdeathp = (target.stat[3] + target.stat[5]) * 100//40
AttributeError: 'Monstergrp' object has no attribute 'stat'

**Comment by achiwa912** [comment]
Fixed.  Will be in the next push.
