### ISSUE TITLE
Exception trying to get one time password

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#47]
Traceback (most recent call last):        ^* north                           ^
  File "/home/achiwa/py/dl/dl.py", line 5101, in <module>
    main()
  File "/home/achiwa/py/dl/dl.py", line 5097, in main
    dispatch(game)
  File "/home/achiwa/py/dl/dl.py", line 5071, in dispatch
    maze(game)
  File "/home/achiwa/py/dl/dl.py", line 4936, in maze
    rt = floor_obj.check_event(game)
  File "/home/achiwa/py/dl/dl.py", line 2342, in check_event
    self.key(game)
  File "/home/achiwa/py/dl/dl.py", line 2301, in key
    game.chest.get_item(key+' key')
  File "/home/achiwa/py/dl/dl.py", line 3804, in get_item
    f"{mem.name} found {self.game.itemdef[item].unident}", start=' ')
KeyError: 'one time password key'

**Comment by achiwa912** [comment]
Fixed.  Will be in the next push.
