### ISSUE TITLE
Exception on going to the dungeon

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#49]
Steps:
1. Start game
2. Resume (save data was in Edge of Town)
3. Go to maze
4. Exception:
Traceback (most recent call last):                                                  
  File "/home/achiwa/py/dl/dl.py", line 5588, in <module>
    main()
  File "/home/achiwa/py/dl/dl.py", line 5584, in main
    dispatch(game)
  File "/home/achiwa/py/dl/dl.py", line 5545, in dispatch
    maze(game)
  File "/home/achiwa/py/dl/dl.py", line 5410, in maze
    vscr.disp_scrwin()
  File "/home/achiwa/py/dl/dl.py", line 287, in disp_scrwin
    floor_obj.put_tile(
AttributeError: 'str' object has no attribute 'put_tile'

**Comment by achiwa912** [comment]
Fixed.  resumed flag wasn't set properly in game.load().  Will be in the next push.
