### ISSUE TITLE
Exception identifying an item at the trader

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#54]
Traceback (most recent call last):                                                
  File "/home/achiwa/py/dl/dl.py", line 5661, in <module>
    main()
  File "/home/achiwa/py/dl/dl.py", line 5657, in main
    dispatch(game)
  File "/home/achiwa/py/dl/dl.py", line 5612, in dispatch
    castle(game)
  File "/home/achiwa/py/dl/dl.py", line 5343, in castle
    trader(game)
  File "/home/achiwa/py/dl/dl.py", line 4992, in trader
    trader_sell(game, mem, ch)
  File "/home/achiwa/py/dl/dl.py", line 4945, in trader_sell
    mem.items[int(c)-1][3] = False  # identified
TypeError: 'tuple' object does not support item assignment

**Comment by achiwa912** [comment]
Fixed.  When loading saved data, it had put member items in tuples.  Changed to put them in lists.  Will be in the next push.
