### ISSUE TITLE
Exception trying to save at Edge of Town

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#55]
Exception during reset or similar                                                 
Traceback (most recent call last):
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139679659607872 and this is thread id 139679406663232.
Exception closing connection <sqlite3.Connection object at 0x7f09a5ecd5d0>
Traceback (most recent call last):
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139679659607872 and this is thread id 139679406663232.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 238, in _close_connection
    self._dialect.do_close(connection)
  File "/home/achiwa/py/dl/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139679659607872 and this is thread id 139679406663232.

**Comment by achiwa912** [comment]
Fixed.  Had not close session or engine.dispose after load from the database in game.load().  Will be in the next push.
