### ISSUE TITLE
spell > view results in an exception

### ISSUE THREAD

**Issue by achiwa912** [achiwa912/daemonlord#75]
Traceback (most recent call last):        ^                                      ^
  File "/home/achiwa/py/dl2/dl.py", line 6495, in <module>
    main()
  File "/home/achiwa/py/dl2/dl.py", line 6491, in main
    dispatch(game)
  File "/home/achiwa/py/dl2/dl.py", line 6274, in dispatch
    maze(game)
  File "/home/achiwa/py/dl2/dl.py", line 6187, in maze
    camp(game, floor_obj)
  File "/home/achiwa/py/dl2/dl.py", line 6046, in camp
    rtn = mem.inspect_character(game)
  File "/home/achiwa/py/dl2/dl.py", line 1750, in inspect_character
    self.spell_menu(game)
  File "/home/achiwa/py/dl2/dl.py", line 1827, in spell_menu
    self.view_spells(game)
  File "/home/achiwa/py/dl2/dl.py", line 1778, in view_spells
    f"{d[name].level} {name.ljust(13)}{d[name].desc[:57]}")
KeyError: ''

**Comment by achiwa912** [comment]
Member.mspells/pspells look to contain  '' (ie, [''] not []).  Where did it come from?

**Comment by achiwa912** [comment]
database member table doesn't have '' in m/spells.  Just after the load(), m/pspells has ''.  load() seems to be the cause.

**Comment by achiwa912** [comment]
Fixed.
